[model]

[model.adapter]
name = "preview-ref"
params = "default"
active_joints = [2, 3, 4, 5]
dt = 0.03333333333
include_dqdes = false

[model.adapter.preview-ref.testing]
ctrl_step = 1
preview_step = 10

[model.adapter.preview-ref.default]
ctrl_step = 1
preview_step = 5

[model.adapter.delay-states.default]
ctrl_step = 1
delay_step = 5

[model.adapter.delay-states-all.default]
ctrl_step = 1
delay_step = 5

[model.scaler]
name = "std"
params = "default"

[model.scaler.std.default]
[model.scaler.minmax.default]
[model.scaler.maxabs.default]
[model.scaler.robust.default]

[model.scaler.std.option-list]
with_mean = true
with_std = true

[model.scaler.minmax.option-list]
feature_range = [0, 1]
clip = false

[model.scaler.maxabs.option-list]
[model.scaler.robust.option-list]
with_centering = true
with_scaling = true
quantile_range = [25.0, 75.0]
unit_variance = false

[model.regressor]
name = "mlp"
params = "default"

[model.regressor.linear.default]
[model.regressor.ridge.default]
[model.regressor.mlp.default]

[model.regressor.linear.option-list]
fit_intercept = true
copy_X = true
n_jobs = "None"
positive = false

[model.regressor.ridge.option-list]
alpha = 1.0
fit_intercept = true
copy_X = true
max_iter = "None"
tol = 1e-4
solver = "auto"
positive = false
random_state = "None"

[model.regressor.mlp.option-list]
hidden_layer_sizes = [100]
activation = "relu"
solver = "adam"
alpha = 0.0001
batch_size = "auto"
learning_rate = "constant"
learning_rate_init = 0.001
power_t = 0.5
max_iter = 200
shuffle = true
random_state = "None"
tol = 1e-4
verbose = false
warm_start = false
momentum = 0.9
nesterovs_momentum = true
early_stopping = false
validation_fraction = 0.1
beta_1 = 0.9
beta_2 = 0.999
epsilon = 1e-8
n_iter_no_change = 10


# Local Variables:
# jinx-local-words: "adam cholesky ctrl dqdes dt init invscaling iter lbfgs lsqr maxabs minmax mlp nesterovs params preprocessing quantile regressor relu scaler sgd svd tanh tol"
# fill-column: 120
# End:
